### ISSUE TITLE
lib.alternative and lib.criteria errors

### ISSUE THREAD

**Issue by Luigiboard** [alfajrimutawadhi/DSS-SAWmethod#1]
these two modules are not loading. Says they is no such modules. Also if you could give an example of how the whole thing is supposed to work i'd really appreciate. Just starting to learn. Thanks

**Comment by alfajrimutawadhi** [comment]
just make sure you have downloaded the required modules in file [README.md](https://github.com/alfajrimutawadhi/DSS-SAWmethod/blob/master/README.md) and execute file main.py. then you can following the instruction
example : 
![image](https://github.com/alfajrimutawadhi/DSS-SAWmethod/assets/68763385/f05d4f2c-65e9-4b27-a062-79fe8845a74a)

I hope you are helped
